CREATE TABLE Department(
   DepartmentId   VARCHAR(4) NOT NULL PRIMARY KEY
  ,DepartmentName VARCHAR(60) NOT NULL
);
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AAS','Asian American Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ABE','Agricultural and Biological Eng');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ACCY','Accountancy');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ACE','Agr & Consumer Economics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ACES','Agr, Consumer, & Env Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ADV','Advertising');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AE','Aerospace Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AFAS','Air Force Aerospace Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AFRO','African American Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AFST','African Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AGCM','Agricultural Communications');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AGED','Agricultural Education');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AHS','Applied Health Sci Courses');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AIS','American Indian Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ALEC','Agricultural Leadership, Education, & Communications Program');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ANSC','Animal Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ANTH','Anthropology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARAB','Arabic');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARCH','Architecture');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ART','Art');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARTD','Art-Design');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARTE','Art-Education');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARTF','Art-Foundation');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARTH','Art-History');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARTJ','Japan House');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ARTS','Art-Studio');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ASRM','Actuarial Science & Risk Management');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ASST','Asian Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ASTR','Astronomy');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ATMS','Atmospheric Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('AVI','Aviation');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BADM','Business Administration');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BASQ','Basque');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BCOG','Brain and Cognitive Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BCS','Bosnian-Croatian-Serbian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BDI','Business Data & Innovation');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BIOC','Biochemistry');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BIOE','Bioengineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BIOL','Biology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BIOP','Biophysics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BSE','Biomedical Sciences and Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BTW','Business and Technical Writing');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BULG','Bulgarian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('BUS','Business');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CAS','Center for Advanced Study');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CATL','Catalan');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CB','Comparative Biosciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CDB','Cell and Developmental Biology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CEE','Civil and Environ Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CHBE','Chemical and Biomolecular Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CHEM','Chemistry');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CHIN','Chinese');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CHLH','Community Health');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CHP','Campus Honors Program');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CI','Curriculum and Instruction');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CIC','Committee on Inst Cooperation');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CINE','Cinema');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CLCV','Classical Civilization');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CLE','Clinical Sciences and Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CMN','Communication');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CPSC','Crop Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CS','Computer Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CSE','Computational Science and Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CW','Creative Writing');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CWL','Comparative & World Literature');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('CZCH','Czech');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('DANC','Dance');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('DTX','Human-Centered Design & Design Thinking');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EALC','East Asian Languages & Cultures');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ECE','Electrical and Computer Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ECON','Economics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EDPR','Educational Practice');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EDUC','Education');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EIL','English as an Intl Language');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ENG','Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ENGH','English');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ENGL','English');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ENSU','Environmental Sustainability');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ENT','Entomology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ENVS','Environmental Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EOL','Educ Organization & Leadership');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EPOL','Ed Policy, Org & Ldership');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EPS','Educational Policy Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EPSY','Educational Psychology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ERAM','Education Research and Methods');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ESE','Earth, Society, & Environment');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ESL','English as a Second Language');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ETMA','Engineering Technology & Management for Agricultural Systems');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('EURO','European Union Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('FAA','Fine and Applied Arts');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('FIN','Finance');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('FLTE','Foreign Language Teacher Education');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('FR','French');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('FSHN','Food Science & Human Nutrition');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GC','Graduate College');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GCL','Graduate College');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GE','General Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GEOG','Geography & Geographic Information Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GEOL','Geology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GER','German');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GLBL','Global Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GMC','Germanic');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GRK','Greek');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GRKM','Modern Greek');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GS','General Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GSD','Game Studies and Design');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('GWS','Gender and Women Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HDES','Human Dimensions of Env Sys');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HDFS','Human Dev and Family Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HEBR','Hebrew, Modern and Classical');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HIST','History');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HNDI','Hindi');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HORT','Horticulture');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HRD','Human Resource Development');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HRE','Human Resources');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HT','Health Technology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('HUM','Humanities Courses');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('IB','Integrative Biology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('IE','Industrial Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('IHLT','IHealth');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('INFO','Informatics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('IS','Information Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ITAL','Italian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('JAPN','Japanese');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('JOUR','Journalism');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('JS','Jewish Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('KIN','Kinesiology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('KOR','Korean');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LA','Landscape Architecture');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LAS','Liberal Arts and Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LAST','Latin American & Caribbean St');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LAT','Latin');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LAW','Law');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LCTL','Less Commonly Taught Languages');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LEAD','Organizational & Community Leadership');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LER','Labor and Employment Relations');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LGLA','Lingala');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LING','Linguistics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('LLS','Latina/Latino Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MACS','Media and Cinema Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MATH','Mathematics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MBA','MBA Program');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MCB','Molecular and Cell Biology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MDIA','Media');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MDVL','Medieval Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ME','Mechanical Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MFST','Metropolitan Food & Environmental Systems');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MICR','Microbiology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MILS','Military Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MIP','Moleculr & Integrative Physiology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MS','Media');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MSE','Materials Science & Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MSP','Medical Scholars Program');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MUS','Music');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MUSC','Music Lessons and Ensembles');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('MUSE','Museum Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('NE','Neural Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('NEUR','Neuroscience');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('NPRE','Nuclear, Plasma, Radiological Engineering');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('NRES','Natural Resources & Environ Sc');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('NS','Naval Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('NUTR','Nutritional Sciences');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PATH','Pathobiology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PBIO','Plant Biology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PERS','Persian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PHIL','Philosophy');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PHYS','Physics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PLPA','Plant Pathology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('POL','Polish');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PORT','Portuguese');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PS','Political Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PSM','Professional Science Master');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('PSYC','Psychology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('QUEC','Quechua');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('REES','Russian, East European and Eurasian Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('REHB','Rehabilitation Counseling');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('REL','Religion');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('RHET','Rhetoric and Composition');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('RLST','Religion');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('RMLG','Romance Linguistics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('RSOC','Rural Society');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('RST','Recreation, Sport, and Tourism');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('RUSS','Russian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SAME','South Asian & Middle Eastern');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SBC','Strategic Brand Communication');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SCAN','Scandinavian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SCR','South Slavic Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SE','Systems Engineering and Design');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SHS','Speech and Hearing Science');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SLAV','Slavic');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SLCL','Literatures Cultures Linguistics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SLS','Student Legal Service');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SNSK','Sanskrit');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SOC','Sociology');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SOCW','Social Work');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SPAN','Spanish');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SPED','Special Education');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('STAT','Statistics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('SWAH','Swahili');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('TAM','Theoretical and Applied Mechanics');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('TE','Technology Entrepreneurship');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('THEA','Theatre');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('TMGT','Technology and Management');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('TRST','Translation Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('TSM','Technical System Management');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('TURK','Turkish');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('UKR','Ukrainian');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('UP','Urban and Regional Planning');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('VB','Pharma');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('VCM','Veterinary Clinical Medicine');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('VM','Veterinary Medicine Courses');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('WGGP','Women and Gender in Global Perspectives');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('WLOF','Wolof');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('WRIT','Writing Studies');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('YDSH','Yiddish');
INSERT INTO Department(DepartmentId,DepartmentName) VALUES ('ZULU','Zulu');
SELECT COUNT(*) FROM Department;